name: Test

on:
    workflow_dispatch:
    push:
        branches: ["*"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21"

            - name: Go Test
              run: go test -v -cover ./...
